// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateExcel(arg1) {
  return window['go']['excel']['ExcelService']['GenerateExcel'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['excel']['ExcelService']['OpenFile'](arg1);
}
